version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - logs:/app/logs
  #     - /app/node_modules

  db:
    build: ./mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  logs:
  mysql_data: