CREATE DATABASE IF NOT EXISTS EDIG_TODO;
USE EDIG_TODO;

CREATE USER IF NOT EXISTS 'edig'@'%' IDENTIFIED BY '3dig_t0D0';

GRANT USAGE ON EDIG_TODO.* TO 'edig'@'%';

CREATE TABLE todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    complete BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO todos(title) VALUES ('Leche'), ('Huevos'), ('Carne');

FLUSH PRIVILEGES;